# Generated by Django 5.1.6 on 2026-08-05 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_seed_setup_lock'),
        ('projects', '0002_project_next_bug_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('name_normalized', models.CharField(editable=False, max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('key', models.CharField(editable=False, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('steps_to_reproduce', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('actual_result', models.TextField(blank=True, default='')),
                ('environment', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('ready_for_qa', 'Ready for QA'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed'), ('blocked', 'Blocked'), ('duplicate', 'Duplicate'), ('cannot_reproduce', 'Cannot reproduce'), ('wont_fix', "Won't fix"), ('deferred', 'Deferred')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('severity', models.CharField(choices=[('blocker', 'Blocker'), ('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='major', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_bugs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='bugs', to='bugs.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BugRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('duplicate_of', 'Duplicate of'), ('blocks', 'Blocks'), ('relates_to', 'Relates to')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='bugs.bug')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('to_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='bugs.bug')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'from_bug'], name='bugs_bugrel_organiz_915adf_idx'), models.Index(fields=['organization', 'to_bug'], name='bugs_bugrel_organiz_65bd06_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_bug', 'to_bug', 'relationship_type'), name='unique_bug_relationship'), models.CheckConstraint(condition=models.Q(('from_bug', models.F('to_bug')), _negated=True), name='bug_relationship_no_self_reference')],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['organization', 'name_normalized'], name='bugs_tag_organiz_db09ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'name_normalized'), name='unique_tag_name_per_org_ci'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'status'], name='bugs_bug_organiz_3a27e0_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'project', 'status'], name='bugs_bug_organiz_df1ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'assignee'], name='bugs_bug_organiz_91a4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'reporter'], name='bugs_bug_organiz_b75f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'archived_at', 'created_at'], name='bugs_bug_organiz_0f7eec_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'priority'], name='bugs_bug_organiz_10e420_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'severity'], name='bugs_bug_organiz_e97d66_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'due_date'], name='bugs_bug_organiz_5b8216_idx'),
        ),
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_bug_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='bug',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_bug_key_per_org'),
        ),
    ]
