# Generated by Django 5.1.6 on 2026-08-05 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
        ('projects', '0002_project_next_bug_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['organization', 'resolved_at'], name='bugs_bug_organiz_beeac0_idx'),
        ),
    ]
