# Generated by Django 5.1.15 on 2026-08-06 18:31, hand-edited — see below.
#
# Enables pg_trgm (a standard PostgreSQL contrib extension, present on every
# supported PostgreSQL install including this project's own postgres:16-alpine
# image — see docs/PERFORMANCE.md "Search findings") before creating the two
# trigram indexes that depend on its gin_trgm_ops operator class. Compatible
# with production PostgreSQL: CREATE EXTENSION IF NOT EXISTS requires only the
# same superuser/rds_superuser-equivalent privilege the initial database setup
# already needs for every other extension-free migration in this project to
# have been applied by *something* — no additional runtime privilege is
# needed by the application itself afterward.
#
# Uses RunSQL instead of the makemigrations-autogenerated AddIndex(GinIndex(
# OpClass(Upper(...)))) directly: Django 5.1's generated SQL for that
# construct is CREATE INDEX ... USING gin ((UPPER("title") gin_trgm_ops)) —
# missing a paren around the expression itself — which PostgreSQL rejects
# outright ("syntax error at or near gin_trgm_ops"), confirmed by running it.
# The correct syntax wraps the expression in its own parens, separate from
# the operator class: ((UPPER("title")) gin_trgm_ops) — verified directly
# against this project's own postgres:16-alpine before being used here.
# state_operations keeps Django's migration *state* (what makemigrations
# diffs against, and what the ORM believes exists) in sync with the model's
# own Meta.indexes, independent of the hand-corrected SQL actually run.

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations

TITLE_INDEX_NAME = "bugs_bug_title_upper_trgm"
KEY_INDEX_NAME = "bugs_bug_key_upper_trgm"


class Migration(migrations.Migration):
    dependencies = [
        ("bugs", "0002_bug_bugs_bug_organiz_beeac0_idx"),
        ("organizations", "0002_seed_setup_lock"),
        ("projects", "0002_project_next_bug_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            sql=(
                f'CREATE INDEX "{TITLE_INDEX_NAME}" ON "bugs_bug" '
                f'USING gin ((UPPER("title")) gin_trgm_ops);'
            ),
            reverse_sql=f'DROP INDEX "{TITLE_INDEX_NAME}";',
            state_operations=[
                migrations.AddIndex(
                    model_name="bug",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("title"), name="gin_trgm_ops"
                        ),
                        name=TITLE_INDEX_NAME,
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=(
                f'CREATE INDEX "{KEY_INDEX_NAME}" ON "bugs_bug" '
                f'USING gin ((UPPER("key")) gin_trgm_ops);'
            ),
            reverse_sql=f'DROP INDEX "{KEY_INDEX_NAME}";',
            state_operations=[
                migrations.AddIndex(
                    model_name="bug",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper("key"), name="gin_trgm_ops"
                        ),
                        name=KEY_INDEX_NAME,
                    ),
                ),
            ],
        ),
    ]
