# Generated by Django 5.1.6 on 2026-08-04 19:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_seed_setup_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Project key must be 2-10 characters, start with a letter, and contain only uppercase letters and digits.', regex='^[A-Z][A-Z0-9]{1,9}$')])),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed')], default='active', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'archived_at'], name='projects_pr_organiz_a0ec73_idx'), models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='unique_project_key_per_org'), models.CheckConstraint(condition=models.Q(('key', django.db.models.functions.text.Upper('key'))), name='project_key_is_uppercase')],
            },
        ),
    ]
