# Generated by Django 5.1.6 on 2026-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='next_bug_number',
            field=models.PositiveIntegerField(default=1, help_text='Next sequential number to assign within this project. Incremented under a row lock (select_for_update) inside apps.bugs.services.create_bug — never read or written anywhere else, so that transaction is the only place this can race.'),
        ),
    ]
