# Generated by Django 5.1.6 on 2026-08-05 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('comments', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('bug_assigned', 'Bug assigned'), ('mentioned', 'Mentioned'), ('comment_added', 'Comment added'), ('status_changed', 'Status changed'), ('bug_reopened', 'Bug reopened')], max_length=20)),
                ('dedup_key', models.CharField(max_length=150)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', max_length=10)),
                ('email_error', models.CharField(blank=True, default='', max_length=500)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bugs.bug')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comments.comment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'recipient', 'read_at'], name='notificatio_organiz_9b2fa8_idx'), models.Index(fields=['organization', 'recipient', '-created_at'], name='notificatio_organiz_ab7ce7_idx'), models.Index(fields=['organization', 'event_type', 'created_at'], name='notificatio_organiz_b7e891_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'recipient', 'dedup_key'), name='unique_notification_dedup'), models.CheckConstraint(condition=models.Q(models.Q(('email_status', 'pending'), ('emailed_at__isnull', True)), models.Q(('email_error', ''), ('email_status', 'sent'), ('emailed_at__isnull', False)), models.Q(('email_error', ''), ('email_status', 'disabled'), ('emailed_at__isnull', True)), models.Q(('email_status', 'failed'), ('emailed_at__isnull', True)), _connector='OR'), name='notification_email_status_consistency'), models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('event_type__in', ['mentioned', 'comment_added'])), ('event_type__in', ['bug_assigned', 'status_changed', 'bug_reopened']), _connector='OR'), name='notification_comment_required_for_comment_events')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('bug_assigned', 'Bug assigned'), ('mentioned', 'Mentioned'), ('comment_added', 'Comment added'), ('status_changed', 'Status changed'), ('bug_reopened', 'Bug reopened')], max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'user'], name='notificatio_organiz_7a76bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user', 'event_type'), name='unique_preference_per_org_user_event')],
            },
        ),
    ]
