# Generated by Django 5.1.6 on 2026-08-05 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('storage_key', models.CharField(editable=False, max_length=500, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('scan_status', models.CharField(choices=[('not_scanned', 'Not scanned'), ('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected')], default='not_scanned', max_length=12)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bugs.bug')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'bug', 'status', 'removed_at'], name='attachments_organiz_a39556_idx'), models.Index(fields=['organization', 'status'], name='attachments_organiz_7b7b98_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', True), ('removed_at__isnull', True), ('status', 'pending'), ('uploaded_at__isnull', True)), models.Q(('failed_at__isnull', True), ('status', 'uploaded'), ('uploaded_at__isnull', False)), models.Q(('failed_at__isnull', False), ('removed_at__isnull', True), ('status', 'failed'), ('uploaded_at__isnull', True)), _connector='OR'), name='attachment_status_timestamp_consistency'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='attachment_size_positive')],
            },
        ),
    ]
