# Generated by Django 5.1.6 on 2026-08-05 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority changed'), ('severity_changed', 'Severity changed'), ('field_updated', 'Field updated'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed'), ('relationship_added', 'Relationship added'), ('relationship_removed', 'Relationship removed'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=32)),
                ('from_value', models.CharField(blank=True, default='', max_length=255)),
                ('to_value', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null means system-generated (e.g. membership removal clearing an assignment).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
