# Generated by Django 5.1.6 on 2026-08-05 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('bugs', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugactivity',
            name='bug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='bugactivity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='bugactivity',
            index=models.Index(fields=['organization', 'bug', '-created_at'], name='activities__organiz_890469_idx'),
        ),
    ]
