# Generated by Django 5.1.6 on 2026-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_bugactivity_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugactivity',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('priority_changed', 'Priority changed'), ('severity_changed', 'Severity changed'), ('field_updated', 'Field updated'), ('tag_added', 'Tag added'), ('tag_removed', 'Tag removed'), ('relationship_added', 'Relationship added'), ('relationship_removed', 'Relationship removed'), ('archived', 'Archived'), ('restored', 'Restored'), ('comment_added', 'Comment added'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('comment_redacted', 'Comment redacted'), ('mention_created', 'Mention created'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed')], max_length=32),
        ),
    ]
