# Generated by Django 5.1.6 on 2026-08-05 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_bugactivity_verb'),
        ('bugs', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bugactivity',
            index=models.Index(fields=['organization', '-created_at'], name='activities__organiz_069dbe_idx'),
        ),
    ]
