# Generated by Django 5.1.15 on 2026-08-06 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_bugactivity_activities__organiz_069dbe_idx"),
        ("bugs", "0002_bug_bugs_bug_organiz_beeac0_idx"),
        ("organizations", "0002_seed_setup_lock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bugactivity",
            index=models.Index(
                fields=["organization", "verb", "to_value", "created_at"],
                name="activities_verb_lookup_idx",
            ),
        ),
    ]
