# Generated by Django 5.1.6 on 2026-08-05 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bugs', '0001_initial'),
        ('organizations', '0002_seed_setup_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('redacted', 'Redacted')], default='active', max_length=10)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('redacted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_comments', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugs.bug')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='comments.comment')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['organization', 'bug', 'created_at'], name='comments_co_organiz_061f90_idx'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('redacted_at__isnull', True), ('status', 'active')), models.Q(('deleted_at__isnull', False), ('redacted_at__isnull', True), ('status', 'deleted')), models.Q(('deleted_at__isnull', True), ('redacted_at__isnull', False), ('status', 'redacted')), _connector='OR'), name='comment_status_timestamp_consistency'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['organization', 'mentioned_user'], name='comments_me_organiz_27b283_idx'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('comment', 'mentioned_user'), name='unique_mention_per_comment_user'),
        ),
    ]
